---
- name: Send webapp tarball
  become: true
  ansible.builtin.copy:
    src: webapp.tar.gz
    dest: /home/isucon/webapp.tar.gz

- name: Mkdir webapp
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp
    state: directory

- name: Mkdir sql
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp/sql
    state: directory

- name: Extract webapp.tar.gz into /home/isucon
  become: true
  become_user: isucon
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/isucon/webapp.tar.gz
    dest: /home/isucon/

- name: Remove webapp.tar.gz
  become: true
  ansible.builtin.file:
    path: /home/isucon/webapp.tar.gz
    state: absent

- name: initilize database
  become: true
  shell: |
    mysql -uroot -e "
      DROP DATABASE IF EXISTS isuride;
      CREATE DATABASE IF NOT EXISTS isuride;
    "
- name: initialize tables
  become: true
  shell: |
    sh /home/isucon/webapp/sql/init.sh

- name: Task for isuride-matcher
  include_tasks: matcher.yaml

- name: Task for isuride-payment_mock
  include_tasks: payment_mock.yaml

- name: Tasks for isuride-go
  include_tasks: go.yaml

- name: Tasks for isuride-node
  include_tasks: node.yaml

- name: Tasks for isuride-perl
  include_tasks: perl.yaml

- name: Tasks for isuride-php
  include_tasks: php.yaml

- name: Tasks for isuride-python
  include_tasks: python.yaml

- name: Tasks for isuride-ruby
  include_tasks: ruby.yaml

- name: Tasks for isuride-rust
  include_tasks: rust.yaml
