---
- name: Mkdir webapp for payment_mock
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp/
    state: directory

- name: Build payment_mock
  become: true
  become_user: isucon
  shell: |
    /home/isucon/local/golang/bin/go build -o /home/isucon/webapp/payment_mock/payment_mock -ldflags "-s -w"
  args:
    chdir: /home/isucon/webapp/payment_mock

- name: Put systemd service
  become: true
  ansible.builtin.copy:
    src: isuride-payment_mock.service
    dest: /etc/systemd/system/

- name: Start payment_mock
  become: true
  service:
    name: isuride-payment_mock
    enabled: true
    state: restarted
