---
- name: Mkdir webapp for ruby
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp/ruby
    state: directory

- name: Build isuride-ruby
  become: true
  become_user: isucon
  shell: |
    /home/isucon/.x bundle install
  args:
    chdir: /home/isucon/webapp/ruby

- name: Put systemd service
  become: true
  ansible.builtin.copy:
    src: isuride-ruby.service
    dest: /etc/systemd/system/

- name: Start webapp
  become: true
  service:
    name: isuride-ruby
    enabled: false
    state: stopped
