---
- name: Mkdir webapp for rust
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp/rust
    state: directory

- name: Build isuride-rust
  become: true
  become_user: isucon
  shell: |
    /home/isucon/.x cargo build --release --locked
  args:
    chdir: /home/isucon/webapp/rust

- name: Put systemd service
  become: true
  ansible.builtin.copy:
    src: isuride-rust.service
    dest: /etc/systemd/system/

- name: Start webapp
  become: true
  service:
    name: isuride-rust
    enabled: false
    state: stopped
