# skaffold.yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: go-app
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-*.yaml
