FROM node:22.11

WORKDIR /home/isucon/webapp/nodejs

RUN apt-get update && apt-get install --no-install-recommends -y \
  default-mysql-client-core=1.1.0 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY . .
RUN npm ci

CMD ["npm", "run", "start"]
