apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    app: random-generator
  ports:
  - name: random
    port: 8080
    protocol: TCP
    targetPort: 7070
  type: NodePort
