# An indexed job that splits up a file
# Run this job after job.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  # Use a generated name so that this descriptor can be 
  # used multiple times with "kubectl create" without conflicts 
  # because of jobs having the same names
  generateName: file-split-
  labels:
    app: random-generator
spec:
  # Completion mode needs to be set to "Indexed"
  completionMode: Indexed
  # Job should run 5 Pods, all in parallel
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: file-split
    spec:
      containers:
      - image: library/perl
        name: split
        command:
        - "perl"
        # -n: Loop over all lines, but don't print by default
        # -e: Execute the following argument as Perl code
        - "-ne"
        - |
          BEGIN {
            # Extract environmwnt variable $JOB_COMPLETION_INDEX
            # set is set for our Indexed job by its controller
            $idx = $ENV{JOB_COMPLETION_INDEX};
            # Open output file with the idx as a suffix (no error handling)
            open($fh,">","/logs/random-${idx}.txt");
          };
          # Print out the current line ($_) to the output file
          # if in the specified range. This code will
          # be executed for every line, with $. set to the actual line number.
          print $fh $_ if $. >= $idx * 10000 && $. < ($idx+1) * 10000;
          END {
            # Close file after the loop
            close($fh)
          }
        # Operate on this file
        - /logs/random.log
        volumeMounts:
        - mountPath: /logs
          name: log-volume
      # Retry again if failed (this field is mandatory)
      restartPolicy: Never
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          # Same volume claim that is referenced in job.yaml
          claimName: random-generator-log
