version: "3"

tasks:
  run-local:
    cmds:
      - go run . run --target http://localhost:8080 -t 60 {{.CLI_ARGS}}
  build:
    cmds:
      - go build -ldflags "-s -w"
  build-linux-amd64:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ./bin/bench_linux_amd64
  test:
    cmds:
      - go test ./...
  image-build:
    cmds:
      - ko build -L .
  gen:
    cmds:
      - go generate ./...
  gen-init-data-sql:
    cmds:
      - go run . generate-init-data
      - mysqldump --skip-create-options --skip-add-drop-table --disable-keys --no-create-info --no-tablespaces -h 127.0.0.1 -u isucon -pisucon --databases isuride -n --ignore-table=isuride.settings --ignore-table=isuride.chair_models | gzip > ../webapp/sql/3-initial-data.sql.gz
  gen-frontend:
    dir: ../frontend
    cmds:
      - pnpm i
      - pnpm run build
