// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Authors    string
	Books      string
	Loans      string
	Publishers string
	Users      string
}{
	Authors:    "authors",
	Books:      "books",
	Loans:      "loans",
	Publishers: "publishers",
	Users:      "users",
}
