psql:
  dbname: "postgres"
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  pass: "postgres"
  sslmode: "disable"
  whitelist:
    - "authors"
    - "publishers"
    - "users"
    - "books"
    - "loans"
