kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # ingress port for nginx
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  # ingress port for cilium
  - containerPort: 31080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31443
    hostPort: 8443
    listenAddress: "0.0.0.0"
    protocol: TCP
  # ingress port for istio
  - containerPort: 32080
    hostPort: 18080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 32443
    hostPort: 18443
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
