- name: Install MySQL
  become: true
  apt:
    name: mysql-server
    state: present

- name: Start mysql service
  service:
    name: mysql
    enabled: true
    state: started

- name: Create isucon user on MySQL
  become: true
  shell: >
    mysql -uroot -e "
      CREATE USER IF NOT EXISTS 'isucon'@'%' IDENTIFIED BY 'isucon';
      GRANT ALL PRIVILEGES ON *.* TO 'isucon'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
    "
