<?php
/**
 * AppGetRides200ResponseRidesInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  IsuRide
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ISURIDE API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IsuRide\Model;

use \ArrayAccess;
use \IsuRide\ObjectSerializer;

/**
 * AppGetRides200ResponseRidesInner Class Doc Comment
 *
 * @category Class
 * @package  IsuRide
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppGetRides200ResponseRidesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'app_get_rides_200_response_rides_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'pickup_coordinate' => '\IsuRide\Model\Coordinate',
        'destination_coordinate' => '\IsuRide\Model\Coordinate',
        'fare' => 'int',
        'chair' => '\IsuRide\Model\AppGetRides200ResponseRidesInnerChair',
        'evaluation' => 'int',
        'requested_at' => 'int',
        'completed_at' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'pickup_coordinate' => null,
        'destination_coordinate' => null,
        'fare' => null,
        'chair' => null,
        'evaluation' => null,
        'requested_at' => 'int64',
        'completed_at' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'pickup_coordinate' => false,
        'destination_coordinate' => false,
        'fare' => false,
        'chair' => false,
        'evaluation' => false,
        'requested_at' => false,
        'completed_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'pickup_coordinate' => 'pickup_coordinate',
        'destination_coordinate' => 'destination_coordinate',
        'fare' => 'fare',
        'chair' => 'chair',
        'evaluation' => 'evaluation',
        'requested_at' => 'requested_at',
        'completed_at' => 'completed_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'pickup_coordinate' => 'setPickupCoordinate',
        'destination_coordinate' => 'setDestinationCoordinate',
        'fare' => 'setFare',
        'chair' => 'setChair',
        'evaluation' => 'setEvaluation',
        'requested_at' => 'setRequestedAt',
        'completed_at' => 'setCompletedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'pickup_coordinate' => 'getPickupCoordinate',
        'destination_coordinate' => 'getDestinationCoordinate',
        'fare' => 'getFare',
        'chair' => 'getChair',
        'evaluation' => 'getEvaluation',
        'requested_at' => 'getRequestedAt',
        'completed_at' => 'getCompletedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('pickup_coordinate', $data ?? [], null);
        $this->setIfExists('destination_coordinate', $data ?? [], null);
        $this->setIfExists('fare', $data ?? [], null);
        $this->setIfExists('chair', $data ?? [], null);
        $this->setIfExists('evaluation', $data ?? [], null);
        $this->setIfExists('requested_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['pickup_coordinate'] === null) {
            $invalidProperties[] = "'pickup_coordinate' can't be null";
        }
        if ($this->container['destination_coordinate'] === null) {
            $invalidProperties[] = "'destination_coordinate' can't be null";
        }
        if ($this->container['fare'] === null) {
            $invalidProperties[] = "'fare' can't be null";
        }
        if ($this->container['chair'] === null) {
            $invalidProperties[] = "'chair' can't be null";
        }
        if ($this->container['evaluation'] === null) {
            $invalidProperties[] = "'evaluation' can't be null";
        }
        if ($this->container['requested_at'] === null) {
            $invalidProperties[] = "'requested_at' can't be null";
        }
        if ($this->container['completed_at'] === null) {
            $invalidProperties[] = "'completed_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id ライドID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets pickup_coordinate
     *
     * @return \IsuRide\Model\Coordinate
     */
    public function getPickupCoordinate()
    {
        return $this->container['pickup_coordinate'];
    }

    /**
     * Sets pickup_coordinate
     *
     * @param \IsuRide\Model\Coordinate $pickup_coordinate pickup_coordinate
     *
     * @return self
     */
    public function setPickupCoordinate($pickup_coordinate)
    {
        if (is_null($pickup_coordinate)) {
            throw new \InvalidArgumentException('non-nullable pickup_coordinate cannot be null');
        }
        $this->container['pickup_coordinate'] = $pickup_coordinate;

        return $this;
    }

    /**
     * Gets destination_coordinate
     *
     * @return \IsuRide\Model\Coordinate
     */
    public function getDestinationCoordinate()
    {
        return $this->container['destination_coordinate'];
    }

    /**
     * Sets destination_coordinate
     *
     * @param \IsuRide\Model\Coordinate $destination_coordinate destination_coordinate
     *
     * @return self
     */
    public function setDestinationCoordinate($destination_coordinate)
    {
        if (is_null($destination_coordinate)) {
            throw new \InvalidArgumentException('non-nullable destination_coordinate cannot be null');
        }
        $this->container['destination_coordinate'] = $destination_coordinate;

        return $this;
    }

    /**
     * Gets fare
     *
     * @return int
     */
    public function getFare()
    {
        return $this->container['fare'];
    }

    /**
     * Sets fare
     *
     * @param int $fare 運賃
     *
     * @return self
     */
    public function setFare($fare)
    {
        if (is_null($fare)) {
            throw new \InvalidArgumentException('non-nullable fare cannot be null');
        }
        $this->container['fare'] = $fare;

        return $this;
    }

    /**
     * Gets chair
     *
     * @return \IsuRide\Model\AppGetRides200ResponseRidesInnerChair
     */
    public function getChair()
    {
        return $this->container['chair'];
    }

    /**
     * Sets chair
     *
     * @param \IsuRide\Model\AppGetRides200ResponseRidesInnerChair $chair chair
     *
     * @return self
     */
    public function setChair($chair)
    {
        if (is_null($chair)) {
            throw new \InvalidArgumentException('non-nullable chair cannot be null');
        }
        $this->container['chair'] = $chair;

        return $this;
    }

    /**
     * Gets evaluation
     *
     * @return int
     */
    public function getEvaluation()
    {
        return $this->container['evaluation'];
    }

    /**
     * Sets evaluation
     *
     * @param int $evaluation 椅子の評価
     *
     * @return self
     */
    public function setEvaluation($evaluation)
    {
        if (is_null($evaluation)) {
            throw new \InvalidArgumentException('non-nullable evaluation cannot be null');
        }
        $this->container['evaluation'] = $evaluation;

        return $this;
    }

    /**
     * Gets requested_at
     *
     * @return int
     */
    public function getRequestedAt()
    {
        return $this->container['requested_at'];
    }

    /**
     * Sets requested_at
     *
     * @param int $requested_at 配車要求日時
     *
     * @return self
     */
    public function setRequestedAt($requested_at)
    {
        if (is_null($requested_at)) {
            throw new \InvalidArgumentException('non-nullable requested_at cannot be null');
        }
        $this->container['requested_at'] = $requested_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return int
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param int $completed_at 評価まで完了した日時
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            throw new \InvalidArgumentException('non-nullable completed_at cannot be null');
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


