name: Link Check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Check links
      run: python .github/check_links.py
