trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildNumber)'

name: "1.0$(Rev:.r)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
            fetchDepth: 1
          - script: ./runtests.sh
            workingDirectory: "$(Build.SourcesDirectory)/CHAP07/testing-terratest/module"
            displayName: "run test"
          - task: PowerShell@2
            displayName: "Tag code"
            inputs:
              targetType: 'inline'
              script: |
                $env:GIT_REDIRECT_STDERR` = '2>&1'
                $tag = "v$(Build.BuildNumber)"
                git tag $tag
                Write-Host "Successfully created tag $tag"
                git push --tags
                Write-Host "Successfully pushed tag $tag"
              failOnStderr: false