---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: curl-allow
  namespace: handson
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl-allow
    version: v1
    content: layer4-authz
  name: curl-allow
  namespace: handson
spec:
  serviceAccountName: curl-allow
  terminationGracePeriodSeconds: 0
  containers:
  - name: curl
    image: curlimages/curl
    command:
    - "/bin/sleep"
    - "1d"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
  restartPolicy: Never
