global:
  imagePullPolicy: IfNotPresent
  logAsJson: true
  defaultPodDisruptionBudget:
    enabled: false
  proxy:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
pilot:
  deploymentLabels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: istio
  podLabels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: istio
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
meshConfig:
  defaultConfig:
    holdApplicationUntilProxyStarts: true
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
sidecarInjectorWebhook:
  templates:
    grpc-simple: ""
    grpc-agent: ""
    waypoint: ""
    kube-gateway: ""
