istio_namespace: istio-system
auth:
  strategy: anonymous
deployment:
  image_pull_policy: IfNotPresent
  ingress_enabled: false
  logger:
    log_format: json
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
external_services:
  custom_dashboards:
    enabled: false
  grafana:
    enabled: false
  prometheus:
    url: http://kube-prometheus-stack-prometheus.prometheus:9090
  istio:
    root_namespace: istio-system
    url_service_version: http://istiod:15014/version
  tracing:
    enabled: false
server:
  metrics_enabled: false
