---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: curl
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl
    version: v1
    content: layer7-authz
    prometheus-monitor-ignore: ""
  name: curl
spec:
  serviceAccountName: curl
  terminationGracePeriodSeconds: 0
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - "/bin/sleep"
      - "1d"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
  restartPolicy: Never
