apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson
  name: handson
spec:
  type: {{.Values.service.type}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: handson
